version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sadaq_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sadaq_user
      POSTGRES_PASSWORD: sadaq_password
      POSTGRES_DB: sadaq_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
